/*

 SRC/BALL.B3.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned  char ball[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x3C,0x3C,0x52,0x6E,0xA1,0xDF,0xA1,0xDF,
  0xA1,0xDF,0x81,0xFF,0x42,0x7E,0x3C,0x3C
};

/* End of SRC/BALL.B3.C */
