#ifndef ZGBMAIN_H
#define ZGBMAIN_H

#define STATES \
_STATE(STATE_SPLASH)\
_STATE(STATE_GAME)\
_STATE(STATE_WIN)\
_STATE(STATE_LEVEL_INTRO)\
STATE_DEF_END

#define SPRITES \
_SPRITE_DMG(SPRITE_PLAYER, player)\
_SPRITE_DMG(SPRITE_BALL,     ball)\
SPRITE_DEF_END

#include "ZGBMain_Init.h"

#endif