#pragma bank 1
#include "ZGBMain.h"
UINT8 init_bank = 1;
UINT8 next_state = STATE_SPLASH;

#define _STATE(STATE_ID) DECLARE_STATE(STATE_ID);
STATES
#undef _STATE

#define _SPRITE(SPRITE_ID, DATA, BANK, SIZE, NFRAMES) DECLARE_SPRITE(SPRITE_ID);
SPRITES
#undef _SPRITE

#define _SPRITE(SPRITE_ID, DATA, BANK, SIZE, NFRAMES) extern unsigned char DATA[];
SPRITES
#undef _SPRITE

SET_N_STATES(N_STATES);
SET_N_SPRITE_TYPES(N_SPRITE_TYPES);

#define _STATE(STATE_ID) INIT_STATE(STATE_ID);
void InitStates() {
	STATES
}
#undef _STATE

#define _SPRITE(SPRITE_ID, DATA, BANK, SIZE, NFRAMES) INIT_SPRITE(SPRITE_ID, DATA, BANK, SIZE, NFRAMES);
void InitSprites() {
	SPRITES
}
#undef _SPRITE